import {
    BellIcon,
    CalendarIcon,
    FileTextIcon,
    GlobeIcon,
    InputIcon,
} from "@radix-ui/react-icons";

export const features = [
    {
        Icon: FileTextIcon,
        name: "Flipkart",
        description: "Title sponsor",
        href: "/",
        cta: "Learn more",
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        className: "col-span-3 lg:col-span-2",
    },
    {
        Icon: InputIcon,
        name: "Google",
        description: "This sponsor",
        href: "/",
        cta: "Learn more",
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        className: "col-span-3 lg:col-span-1",
    },
    {
        Icon: GlobeIcon,
        name: "PhonePe",
        description: "This sponsor",
        href: "/",
        cta: "Learn more",
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        className: "col-span-3 lg:col-span-1",
    },
    {
        Icon: CalendarIcon,
        name: "Realme",
        description: "This sponsor",
        href: "/",
        cta: "Learn more",
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        className: "col-span-3 lg:col-span-1",
    },
    {
        Icon: BellIcon,
        name: "Boat",
        description: "This sponsor",
        href: "/",
        cta: "Learn more",
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        className: "col-span-3 lg:col-span-1",
    },
    {
        Icon: GlobeIcon,
        name: "Paytm",
        description: "This sponsor",
        href: "/",
        cta: "Learn more",
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        className: "col-span-3 lg:col-span-1",
    },
    {
        Icon: CalendarIcon,
        name: "Lenskart",
        description: "This sponsor",
        href: "/",
        cta: "Learn more",
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        className: "col-span-3 lg:col-span-1",
    },
    {
        Icon: BellIcon,
        name: "Noise",
        description: "This sponsor",
        href: "/",
        cta: "Learn more",
        background: <img className="absolute -right-20 -top-20 opacity-60" />,
        className: "col-span-3 lg:col-span-1",
    },
];