import React from 'react'
import BlogListCard from './BlogListCard'

const BlogListGrid = () => {
  return (
    <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 w-[88rem] gap-8 md:gap-10 mx-5'>
            <div><BlogListCard image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSujiuIp40oRg8BHrZPURhWblHvAX4XKMcVxA&s" date="11 July 2024" blog_title="Scaling up" blog_content="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate itaque omnis est molestias provident, nesciunt soluta vitae, quia earum maxime sapiente repellat debitis. Qui eum delectus eveniet molestias voluptates laudantium." tags={["Entrepreneurship","startup"]}/></div>
            <div><BlogListCard image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSujiuIp40oRg8BHrZPURhWblHvAX4XKMcVxA&s" date="11 July 2024" blog_title="Scaling up" blog_content="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate itaque omnis est molestias provident, nesciunt soluta vitae, quia earum maxime sapiente repellat debitis. Qui eum delectus eveniet molestias voluptates laudantium." tags={["Entrepreneurship","startup"]}/></div>
            <div><BlogListCard image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSujiuIp40oRg8BHrZPURhWblHvAX4XKMcVxA&s" date="11 July 2024" blog_title="Scaling up" blog_content="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate itaque omnis est molestias provident, nesciunt soluta vitae, quia earum maxime sapiente repellat debitis. Qui eum delectus eveniet molestias voluptates laudantium." tags={["Entrepreneurship","startup"]}/></div>
            <div><BlogListCard image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSujiuIp40oRg8BHrZPURhWblHvAX4XKMcVxA&s" date="11 July 2024" blog_title="Scaling up" blog_content="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate itaque omnis est molestias provident, nesciunt soluta vitae, quia earum maxime sapiente repellat debitis. Qui eum delectus eveniet molestias voluptates laudantium." tags={["Entrepreneurship","startup"]}/></div>
            <div><BlogListCard image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSujiuIp40oRg8BHrZPURhWblHvAX4XKMcVxA&s" date="11 July 2024" blog_title="Scaling up" blog_content="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate itaque omnis est molestias provident, nesciunt soluta vitae, quia earum maxime sapiente repellat debitis. Qui eum delectus eveniet molestias voluptates laudantium." tags={["Entrepreneurship","startup"]}/></div>
            <div><BlogListCard image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSujiuIp40oRg8BHrZPURhWblHvAX4XKMcVxA&s" date="11 July 2024" blog_title="Scaling up" blog_content="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate itaque omnis est molestias provident, nesciunt soluta vitae, quia earum maxime sapiente repellat debitis. Qui eum delectus eveniet molestias voluptates laudantium." tags={["Entrepreneurship","startup"]}/></div>
            <div><BlogListCard image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSujiuIp40oRg8BHrZPURhWblHvAX4XKMcVxA&s" date="11 July 2024" blog_title="Scaling up" blog_content="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate itaque omnis est molestias provident, nesciunt soluta vitae, quia earum maxime sapiente repellat debitis. Qui eum delectus eveniet molestias voluptates laudantium." tags={["Entrepreneurship","startup"]}/></div>
            <div><BlogListCard image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSujiuIp40oRg8BHrZPURhWblHvAX4XKMcVxA&s" date="11 July 2024" blog_title="Scaling up" blog_content="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate itaque omnis est molestias provident, nesciunt soluta vitae, quia earum maxime sapiente repellat debitis. Qui eum delectus eveniet molestias voluptates laudantium." tags={["Entrepreneurship","startup"]}/></div>
            <div><BlogListCard image_url="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSujiuIp40oRg8BHrZPURhWblHvAX4XKMcVxA&s" date="11 July 2024" blog_title="Scaling up" blog_content="Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate itaque omnis est molestias provident, nesciunt soluta vitae, quia earum maxime sapiente repellat debitis. Qui eum delectus eveniet molestias voluptates laudantium." tags={["Entrepreneurship","startup"]}/></div>
    </div>
  )
}

export default BlogListGrid
